# Generated by Django 5.0 on 2023-12-27 18:01

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                default="cover.jpg",
                null=True,
                upload_to=userauths.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to=userauths.models.user_directory_path,
            ),
        ),
    ]
