# Generated by Django 5.0 on 2023-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0003_alter_profile_cover_image_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
