# Generated by Django 5.0 on 2023-12-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
