# Generated by Django 5.0 on 2023-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery", options={"verbose_name_plural": "Gallery"},
        ),
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("Only Me", "Only Me"), ("Everyone", "Everyone")],
                default="Everyone",
                max_length=100,
            ),
        ),
    ]
