# Generated by Django 5.0 on 2023-12-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_gallery_options_alter_post_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
