# Generated by Django 5.0 on 2023-12-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                max_length=1000,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.comment",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.post"
            ),
        ),
    ]
