# Generated by Django 5.0 on 2024-02-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_historyy_history"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="slug",),
    ]
