# Generated by Django 5.0 on 2024-03-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_history_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage", old_name="reciever", new_name="receiver",
        ),
    ]
