# Generated by Django 5.0 on 2024-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_reciever_chatmessage_receiver"),
    ]

    operations = [
        migrations.RemoveField(model_name="chatmessage", name="user",),
    ]
